# Generated by Django 4.0 on 2023-06-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takeappointment',
            name='amount_per_member',
        ),
        migrations.RemoveField(
            model_name='takeappointment',
            name='total_members',
        ),
        migrations.AddField(
            model_name='generateticket',
            name='appointment_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='takeappointment',
            name='adult_cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='takeappointment',
            name='children_cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='takeappointment',
            name='no_of_adults',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='takeappointment',
            name='no_of_children',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='takeappointment',
            name='shooting_cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='takeappointment',
            name='visitor_type',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='visitor_type',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='generateticket',
            name='date',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='generateticket',
            name='ticket_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='generateticket',
            name='time',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='password',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='utype',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='mobile_no',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
