# Generated by Django 4.0 on 2023-06-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_otpcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_type', models.IntegerField()),
                ('adult_cost', models.IntegerField()),
                ('children_cost', models.IntegerField()),
            ],
        ),
    ]
