# Generated by Django 4.0 on 2023-06-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_pricemaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricemaster',
            name='visitor_type',
            field=models.CharField(max_length=100),
        ),
    ]
