# Generated by Django 4.0 on 2023-07-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_takeappointment_payment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generateticket',
            old_name='terms_condition',
            new_name='qrcode',
        ),
        migrations.AddField(
            model_name='generateticket',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='generateticket',
            name='payment_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='id_proof',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
