# Generated by Django 4.0 on 2023-07-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_terms_condition_generateticket_qrcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generateticket',
            name='time',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
