# Generated by Django 4.0 on 2023-07-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_generateticket_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generateticket',
            name='qrcode',
            field=models.FileField(null=True, upload_to='docs'),
        ),
    ]
