# Generated by Django 4.0 on 2023-07-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_generateticket_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takeappointment',
            name='shooting_cost',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
