# Generated by Django 4.0 on 2023-07-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_takeappointment_shooting_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takeappointment',
            name='shooting_cost',
            field=models.IntegerField(null=True),
        ),
    ]
