# Generated by Django 4.0 on 2023-07-17 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_generateticket_qrcode'),
        ('home', '0012_alter_takeappointment_shooting_cost'),
    ]

    operations = [
    ]
